sudo: required

services:
  - docker

compiler:
  - gcc

before_install:
  - docker pull absalomedia/hhvm-dev
  - docker ps -a
   -sudo docker info

install:
- mkdir ${TRAVIS_BUILD_DIR}/newrelic
- cd ${TRAVIS_BUILD_DIR}/newrelic
- wget https://download.newrelic.com/agent_sdk/nr_agent_sdk-v0.16.1.0-beta.x86_64.tar.gz
- tar -xzf nr_agent_sdk-*.tar.gz
- sudo cp nr_agent_sdk-*/include/* /usr/local/include/
- sudo cp nr_agent_sdk-*/lib/* /usr/local/lib/
- mkdir ${TRAVIS_BUILD_DIR}/BUILD
- cd ${TRAVIS_BUILD_DIR}/BUILD
- wget http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz
- tar xvf ocaml-4.02.1.tar.gz
- cd ocaml-4.02.1
- ./configure
- make world.opt
- sudo make install
- cd ${TRAVIS_BUILD_DIR}/BUILD
- git clone git://github.com/bagder/curl.git --depth=1
- cd curl
- ./buildconf
- ./configure --prefix=$CMAKE_PREFIX_PATH
- make
- sudo make install
- cd ${TRAVIS_BUILD_DIR}/BUILD
- wget http://launchpadlibrarian.net/80433359/libgoogle-glog0_0.3.1-1ubuntu1_amd64.deb
- sudo dpkg -i libgoogle-glog0_0.3.1-1ubuntu1_amd64.deb
- rm libgoogle-glog0_0.3.1-1ubuntu1_amd64.deb
- wget http://launchpadlibrarian.net/80433361/libgoogle-glog-dev_0.3.1-1ubuntu1_amd64.deb
- sudo dpkg -i libgoogle-glog-dev_0.3.1-1ubuntu1_amd64.deb
- rm libgoogle-glog-dev_0.3.1-1ubuntu1_amd64.deb
- cd ${TRAVIS_BUILD_DIR}/BUILD
- wget http://ubuntu.mirrors.tds.net/ubuntu/pool/universe/j/jemalloc/libjemalloc1_3.6.0-2_amd64.deb
- sudo dpkg -i libjemalloc1_3.6.0-2_amd64.deb
- rm libjemalloc1_3.6.0-2_amd64.deb
- wget http://ubuntu.mirrors.tds.net/ubuntu/pool/universe/j/jemalloc/libjemalloc-dev_3.6.0-2_amd64.deb
- sudo dpkg -i libjemalloc-dev_3.6.0-2_amd64.deb
- rm libjemalloc-dev_3.6.0-2_amd64.deb
- export CXX="g++-4.9"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - hhvm --version
  - hphpize
  - cmake .
  - make
  - make install

notifications:
    on_success: never
    on_failure: never

os:
  - linux
